<a href="https://colab.research.google.com/github/gusainnikhil02-create/NEURAL-NETWORK-ASSIGNMENT-2/blob/main/Project_2_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Take a dataset from Kaggle and perform preprocessing using ANN and CNN concept?

In [ ]:
import pandas as pd

data = pd.read_csv('TopRichestInWorld.csv')

print("Data loaded from TopRichestInWorld.csv")
# Show first 5 rows
data.head()

Data loaded from TopRichestInWorld.csv

,Name,NetWorth,Age,Country/Territory,Source,Industry
0,Elon Musk,"$219,000,000,000",50,United States,"Tesla, SpaceX",Automotive
1,Jeff Bezos,"$171,000,000,000",58,United States,Amazon,Technology
2,Bernard Arnault & family,"$158,000,000,000",73,France,LVMH,Fashion & Retail
3,Bill Gates,"$129,000,000,000",66,United States,Microsoft,Technology
4,Warren Buffett,"$118,000,000,000",91,United States,Berkshire Hathaway,Finance & Investments

In [ ]:
# Check missing values
print("Missing values before filling/dropping:")
display(data.isnull().sum())
display(data.head())

# Fill missing 'Age' values with the mean if there are any
if data['Age'].isnull().any():
    data['Age'].fillna(data['Age'].mean(), inplace=True)
    print("Missing 'Age' values filled with mean.")

# Drop 'Name' column if it exists (assuming it's not needed for analysis)
if 'Name' in data.columns:
    data.drop(['Name'], axis=1, inplace=True)
    print("'Name' column dropped.")

Missing values before filling/dropping:

NetWorth             0
Age                  0
Country/Territory    0
Source               0
Industry             0
dtype: int64

       NetWorth  Age  Country/Territory  Source  Industry
0  2.190000e+11   50                 18      20         0
1  1.710000e+11   58                 18       1        14
2  1.580000e+11   73                  5      14         3
3  1.290000e+11   66                 18      15        14
4  1.180000e+11   91                 18       4         4

In [ ]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Select the numerical columns to scale
# Assuming 'NetWorth' and 'Age' are the numerical columns that need scaling
numerical_cols = ['NetWorth', 'Age']

# Apply StandardScaler to the numerical columns
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])

print("Numerical features ('NetWorth' and 'Age') have been scaled using StandardScaler.")
display(data.head())
display(data.info())

Numerical features ('NetWorth' and 'Age') have been scaled using StandardScaler.

   NetWorth       Age  Country/Territory  Source  Industry
0  4.951584 -1.238366                 18      20         0
1  3.606020 -0.659650                 18       1        14
2  3.241596  0.425442                  5      14         3
3  2.428650 -0.080934                 18      15        14
4  2.120292  1.727553                 18       4         4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NetWorth           101 non-null    float64
 1   Age                101 non-null    float64
 2   Country/Territory  101 non-null    int64
 3   Source             101 non-null    int64
 4   Industry           101 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 4.1 KB

None

In [ ]:
from sklearn.model_selection import train_test_split

X = data.drop('NetWorth', axis=1)  # Use all other columns as features
y = data['NetWorth']  # 'NetWorth' as the target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data split into training and testing sets successfully.")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

Data split into training and testing sets successfully.
X_train shape: (80, 4)
X_test shape: (21, 4)
y_train shape: (80,)
y_test shape: (21,)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the ANN model
model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='linear')
])

print("ANN model defined successfully.")
model.summary()

ANN model defined successfully.

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 225 (900.00 B)

 Trainable params: 225 (900.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mean_absolute_error']
)

In [ ]:
model.fit(X_train, y_train, epochs=20, batch_size=32)

Epoch 1/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 1.1090 - mean_absolute_error: 0.8991
Epoch 2/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0525 - mean_absolute_error: 0.8680
Epoch 3/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0039 - mean_absolute_error: 0.8387
Epoch 4/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9595 - mean_absolute_error: 0.8125
Epoch 5/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9200 - mean_absolute_error: 0.7909
Epoch 6/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.8816 - mean_absolute_error: 0.7706
Epoch 7/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.8513 - mean_absolute_error: 0.7533
Epoch 8/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.8200 - mean_absolute_error: 0.7359
Epoch 9/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7938 - mean_absolute_error: 0.7203
Epoch 10/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7686 - mean_absolute_error: 0.7061
Epoch 11/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.7492 - mean_absolute_error: 0.6914
Epoch 12/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.7281 - mean_absolute_error: 0.6779
Epoch 13/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.7107 - mean_absolute_error: 0.6667
Epoch 14/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6957 - mean_absolute_error: 0.6544
Epoch 15/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 0.6816 - mean_absolute_error: 0.6452
Epoch 16/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.6673 - mean_absolute_error: 0.6357
Epoch 17/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.6571 - mean_absolute_error: 0.6270
Epoch 18/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.6451 - mean_absolute_error: 0.6185
Epoch 19/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.6351 - mean_absolute_error: 0.6111
Epoch 20/20
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 0.6275 - mean_absolute_error: 0.6052

In [ ]:
loss, mae = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Mean Absolute Error:", mae)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.8824 - mean_absolute_error: 0.9018
Loss: 1.8824219703674316
Mean Absolute Error: 0.9018245935440063